name: Go

on:
  push:
    branches: [ main, development ]
    paths:
      - '.github/workflows/go.yml'
      - 'server/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      working-directory: ./server
      run: go build -v

    - name: Run vet
      working-directory: ./server
      run: go vet

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      working-directory: ./server
      run: go test ./...

  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
   
    runs-on: ubuntu-latest
    needs: [ build, test ]
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Cloud Auth
      id: auth
      uses: google-github-actions/auth@v0
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ secrets.GCLOUD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCLOUD_SERVICE_ACCOUNT }}'

    # Authenticate Docker to Google Cloud Artifact Registry
    - name: Docker Auth
      id: docker-auth
      uses: docker/login-action@v2
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: 'europe-west1-docker.pkg.dev'

    - name: Build and Push Container
      working-directory: ./server
      run: |-
        docker build -t "europe-west1-docker.pkg.dev/mezzonic-solver/mezzonic-solver/mezzonic-solver" .
        docker push "europe-west1-docker.pkg.dev/mezzonic-solver/mezzonic-solver/mezzonic-solver"

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: mezzonic-solver
        region: europe-west1
        image: europe-west1-docker.pkg.dev/mezzonic-solver/mezzonic-solver/mezzonic-solver
        env_vars: FRONTEND_URL=${{ secrets.FRONTEND_URL }}
        timeout: 30s
