name: Go

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'server/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      working_directory: ./server
      run: go build -v

    - name: Run vet
      working_directory: ./server
      run: go vet

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: 'mezzonic-solver'
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: 'server'
        dontautocreate: true
        dontuseforce: true
